### ISSUE TITLE
A potential approach for checking if a datum is done

### ISSUE THREAD

**Issue by CJ-Wright** [python-streamz/streamz#299]
One way to think about check pointing is knowing if a piece of data has completely exited the pipeline, it is no longer being processed or being held in a cache.

Backpressure can help out here, since we can know if the pipeline has returned control up the call stack.

I think there are three ways that control is returned:
1. All computations have finished, the data has left through a sink
2. Some computations have finished, the data was dropped by a filter
3. Some computations have finished, the data was stored in a cache waiting for something

1 and 2 are handled by backpressure nicely, since if all the computations have finished then the data is done.

3 is a bit more tricky since we need to track the cached values. 

Potential implementation

```python
def _emit(..., metadata={'reference': RefCounter}):
    RefCounter += len(self.downstreams)
    for downstream in downstream:
        downstream.update(x)
        RefCounter -= 1
```
Caching nodes
```python
def update(...):
    cache.append(x)
    RefCounter += 1
```
When the RefCounter hits zero the data is done.

Note that this would need to merge the refcounting metadata when joining nodes. For instance `combine_latest` would need to propagate the ref counters for all incoming data sources, and all downstream data consumers would need to increment/decrement for all the ref counters.

We'd also need to make the refcounters at data ingestion time.

**Comment by CJ-Wright** [comment]
xref: #297 #278 #272 
CC: @jsmaupin , @chinmaychandak, @satishvarmadandu

This is just a potential architecture, more me attempting to keep some written notes of what I was thinking about.

**Comment by jsmaupin** [comment]
So, in this case the source needs to continuously monitor these reference counters and wait until they hit zero?

It seems like futures are a good approach here because they work well with the asynchronous mechanics of the library.

**Comment by CJ-Wright** [comment]
You could add a callback to the reference counter, when the counter hits zero alert anything that wants to know that the data is finished.

**Comment by martindurant** [comment]
A future, associated with the reference counter, which the counter "completes" when references reach zero. This counter class then holds the arbitrary metadata we have talked about, and, effectively, cause callbacks (all async). Am I talking madness?

**Comment by CJ-Wright** [comment]
Futures could be a good way to handle the callback

**Comment by chinmaychandak** [comment]
Do we absolutely _need_ references to solve checkpointing? I think other than caching nodes, the current implementation with futures works fine. It's just that futures logic would need to be changed a little in caching nodes, like @CJ-Wright pointed out. 

Also, for now, a future is a Torando object. Later on, if we do indeed find a use case for passing on metadata and not just a future, we could just easily replace a Future with a custom Class object which encapsulated the Future.

**Comment by jsmaupin** [comment]
I think what would help here is just to nail down why this approach is better than the one posted in the recent PR.  Is it simpler and more concise?  Is it less prone to error? If so, how?

**Comment by satishvarmadandu** [comment]
@CJ-Wright .. As @jsmaupin mentioned about solving futures with combine_latest() .. i believe that will address handling futures for cache_nodes() right. Its like we replace corresponding futures omnce we get data from the corresponding stream. This way we hold onto to futures

Reference counting is good idea and i beleive that compliments futures right. So can we say futures is the first foundation and we can improve the foundation by adding referencing counting later depending on the use case ?

**Comment by satishvarmadandu** [comment]
Agree with @jsmaupin .. it would be great to nail down the approach. Is this (a) futures (AND) reference counting or (b) futures (or) reference counting

**Comment by CJ-Wright** [comment]
@chinmaychandak my understanding is that the current PR implementation lacks multi-downstream support, in addition to cache handling.

To some extent I think using the `future` object may be overkill, and may include some interfaces that might not be helpful. For instance what does `cancel` mean in this context? What about `set_exception`?

My understanding is that the approach to handling multiple downstreams is to [create multiple futures](https://github.com/python-streamz/streamz/pull/297#issuecomment-574439274) and then check if all the futures are done. This is essentially counting if the number of done futures equals the total number of futures. This is essentially reference counting, done with a bunch of futures objects.

The downside of this approach is that now all these futures objects need to be centralized in the source so it can check if all the futures are done. This requires communication with the source from every node which may have multiple downstreams. I think this breaks some of the elegance of the library, since almost all the nodes only are concerned with their direct upstreams or downstreams. Very few nodes access completely different parts of the graph.

While futures fit well with the async part of streamz, they may not make sense in a non-asynchronous workflow, which streamz also supports. It would be cleaner if streamz supported both using the same infrastructure.

To my mind the state of a piece of data isn't really an aspect of the source of the data, it is much more about the data itself. Thus, having the "done-ness" associated with the data itself rather than the source, provides greater flexibility, since consumers beyond the source could be interested if a piece of data has finished processing.

I think @martindurant's approach seems reasonable,  since it provides good separation between "is this datum done" and "who wants to know if this is done". I'm not certain if we need the full power of the futures interface for that to work, we may just need a counter with a list of callables, but both may work.

**Comment by martindurant** [comment]
I think I agree with everything @CJ-Wright said here.

> I'm not certain if we need the full power of the futures interface for that to work, we may just need a counter with a list of callables, but both may work.

Actually, I think you might, since the callback should ideally be done async, i.e., you don't necessarily want the update on a sink to call a (blocking) chain of things back in the source.

**Comment by martindurant** [comment]
Maybe other futures things do make sense in the long run for that model: `cancel`: the data is rejected by the sink or otherwise wasn't processed, `exception`: something went wrong preventing processing...

But still I would understand just stashing the source method which should be the "done" callback, for the sake of simplicity.

**Comment by jsmaupin** [comment]
By "stashing the source method" you mean, each downstream node would have a reference to a "done callback" in the source node?

**Comment by martindurant** [comment]
No, I imagine the referencecounter object has the callback as an attribute (in the simple case), but its the referencecounter that gets passed around.

**Comment by satishvarmadandu** [comment]
@CJ-Wright thanks for the detailed explanation. Agree that we need handle both "async" & "sync" usecases in the similar way. With that said, is the suggestion is to implement (a) "Only" reference counting instead of futures or (b) both reference counting and futures. I feel both might be an overkill 

@martindurant .. for referencecounter object, how do we tie reference counter object with tornado futures .... everytime we create a new future or complete future in the pipeline, we increment/decrement reference counters ? so we need to have some tight coupling between futures & reference counter objects ..

**Comment by martindurant** [comment]
No, I would presume that the referencecounter only creates one future, associated with the work to be done then the references go to zero. From the source's point of view, the status of this future represents whether the data it is shepherding  is done with or not. It could either associate a callback with it, or add a coroutine to the ioloop which simply awaits on the future.

**Comment by jsmaupin** [comment]
Hey @martindurant and @CJ-Wright, thanks for your help on this. I'm currently writing a proposal to lay everything out nice and clear before we implement this. I think everything makes sense except for one item.  How do we handle the metadata when we are combining two streams into one.  In the case of `combine_latest`, we will have two sets of metadata incoming, but we will only be emiting one?  How do we combine the metadata?

**Comment by jsmaupin** [comment]
I thought about this some more. I believe the `combine_latest` would manage one reference counter while the `Stream` base class would manage the other in the `_emit()` function. Does this sound right?

**Comment by CJ-Wright** [comment]
I think one potential way to handle `combine_latest` would pass through a container of reference counters, so that each reference counter gets incremented. When data comes into `combine_latest` or other nodes that join multiple edges it could send that container of reference counters downstream.

**Comment by jsmaupin** [comment]
So, the metadata would not hold a reference counter, but a container of reference counters. And, the container will most likely be something like a list?

**Comment by CJ-Wright** [comment]
I think having the logic to handle both would be good, or we can standardize around a list of reference counters.

**Comment by jsmaupin** [comment]
I would like to implement this reference counter idea. As deadlines are looming on our side, I would like to make everything clear and get everyone on-board with how things will work before we start writing code.

Firstly, after thinking about this, it seems the reference counters idea is much simpler to implement will handle the multiple down-streams configuration much more elegantly than the previous PR where we were using futures to know when data is done. Thanks for proposing this.

Additionally, passing metadata along with the data seems like a good idea for features in the future which are not specified at this time.

If a pipeline in Streamz were nothing but calls to `map()`, then we would not need to implement anything to know when data is done. We would set up the pipeline as such.

```python
source = Stream()
L = source.map(foo1).map(foo2).map(foo3).sink_to_list()
source.emit(1)
source.emit(2)
source.emit(3)
source.emit(4)
```
Each emit call would block until the data has exited the `sink_to_list()` call.

However, there are nodes that cache the data such as `buffer()` and `combine_latest()`. These nodes will return without passing the data downstream. This will unravel the call stack, and the call to `emit()` will return before the data exits the stream. Some of these nodes will emit the data downstream at some unspecified time in the future. This makes it hard to know when data is done being processed. To illustrate, the example above would interact with the call stack in the following way where the stack would grow at each time interval:

```
t8: return
t7: sink.update()  call stack offset: 7
t6: stream._emit() call stack offset: 6
t5: map3.update()  call stack offset: 5
t4: stream._emit() call stack offset: 4
t3: map2.update()  call stack offset: 3
t2: stream._emit() call stack offset: 2
t1: map1.update()  call stack offset: 1
t0: source._emit() call stack offset: 0
```

After `t8`, the stack would unravel and `emit()` would return in the user's application. However, with the use of `buffer()`, the call stack would not continue to grow until the end of the stream. It would unravel early. And cause `emit()` to return before data exits the stream.

```python
source = Stream()
L = source.map(foo1).buffer(foo2).sink_to_list()
```

```
t4: return
t3: buffer.update() call stack offset: 3
t2: stream._emit()  call stack offset: 2
t1: map.update()    call stack offset: 1
t0: source._emit()  call stack offset: 0
```

In order to reconcile this issue, the proposed solution is to have a reference counter which would track how many nodes are currently holding references to a given datum. The processing on a given datum is considered to be done once the reference count reaches zero. The mapping of datum to metadata is 1:1. So, in the previous example, a reference counter could be passed to the `buffer()` node and the `buffer()` node could increment the reference count by 1 indicating that the datum is still being processed. When `buffer()` is ready to continue to emit the data downstream, it will decrement the counter by 1 after calling `_emit()` to ensure that there is no time when the counter is zero before the data is done. This last detail is important. We do not want the reference counter to report zero references when the data is still in the pipeline.

So, the reference counter would alter the previous example like so:

```
tn+2: return                                               ref: 0
tn+1: sink.update()                 call stack offset: 1   ref: 2   
tn+0: stream._emit() # from buffer  call stack offset: 0   ref: 2                       
t4:   return                                               ref: 1
t3:   buffer.update()               call stack offset: 3   ref: 3 
t2:   stream._emit()                call stack offset: 2   ref: 2
t1:   map.update()                  call stack offset: 1   ref: 1
t0:   source._emit()                call stack offset: 0   ref: 1
```

In another example, `combine_latest()` takes two streams as inputs. We can have two streams: `a` and `b`. If data is received in `a`, a tuple will be emitted with the input from `a` and the last received input from `b`. This means that the node will hold on to any incoming data elements, so a reference will need to be incremented for each. When the data changes, the reference counter can be decremented.

However, in this latest example, we can see that that with two streams being combined into a single emitted tuple, there will need to be some way to combine metadata from all incoming streams to accompany the single emitted element. The proposed solution is to use a container for the reference counters rather than the bare reference itself. Namely, this container will be a list type. The incoming reference counters will all be emitted downstream, and the `Stream` class will need to have functionality to handle the both the case of a bare reference counter or a container holding a collection of reference counters.

**Comment by CJ-Wright** [comment]
@jsmaupin looks good! I think the only detail missing is that when the reference counter drops to zero it needs to inform any interested parties of that. I like @martindurant plan of using callback(s) to handle this. This informing step will allow the kafka system(s) to update their offsets.

**Comment by jsmaupin** [comment]
I think we need to clarify how the source becomes notified that the ref count reaches zero.  We have two options here:

1. Use callbacks
2. Use futures

With the callback, the source will provide a function to call, which seems to me like we would need a wrapper function so that the reference object will call the callback with the right parameters. For example:

```python
class Ref:
    def __init__(self, cb, etc...):
        self.cb = cb

    def dec(self, x):
        self.count -= x
        if x <= 0:
            self.loop.add_callback(self.cb)

def cb(partition, offset):
    # commit the offsets

# in the source
Ref(lambda _: cb(partition, offset))

Futures will be similar. The source will pass a future and wait for the reference counter to signal completion.  

Is anything wrong here?  Are futures the right answer here?  Does anyone have a preference? 
```

**Comment by martindurant** [comment]
A future is just a callback you can await on, right? That would mean that the producing source could register its actions as coroutines, and have tornado figure out when to execute them. A callback *function* could also be a coroutine, so no real difference - or it could be a regular function.

**Comment by jsmaupin** [comment]
Right, so there's a myriad of ways to do this.  My approach in the futures PR was to have the source execute everything in a tornado callback, create a future, pass it downstream and await on it.  We could take the same approach here.  What do you think?

**Comment by jsmaupin** [comment]
@CJ-Wright do you have an opinion on this?

**Comment by CJ-Wright** [comment]
I don't really have an opinion on the actual implementation approach, to some extent we may need to refactor things as we go along and run into issues. My only real comment is that we should at least leave ourselves the option to have multiple callbacks/function calls once the data  is finished. It doesn't need to be implemented that way, but a potential path to do that would be great.

**Comment by chinmaychandak** [comment]
The RefCounter implementation aside — Do we keep the `test_core.py` file as is, and create a new file for checkpointing tests for every node? Or should we just add RefCounter-related assertions by modifying the existing tests? 

Does anyone have a preference?

**Comment by martindurant** [comment]
I would certainly suggest that the current tests remain unchanged, and indeed that nodes which are passed data that don't need to be ref-counted function exactly as before.

**Comment by chinmaychandak** [comment]
> I would certainly suggest that the current tests remain unchanged, and indeed that nodes which are passed data that don't need to be ref-counted function exactly as before.

@martindurant We would be adding a ref-counter test for each node, both caching and non-caching (along with adding tests to `test_kafka.py` for checkpointing). Creating new tests for each node would duplicate code?

**Comment by martindurant** [comment]
I don't think you need a test for every node class, but use the kafka case (or other simpler test source which has checkpointing) and a simple function, with each type of node (caching, non-caching, combine latest) and perhaps a couple of more complex node graphs.

**Comment by jsmaupin** [comment]
I would like to post a progress update and a bit of breakdown on the problem.

Previously, and for the purposes here, we have categorized the two types of functions in Streamz as cache nodes and non-cache nodes. I think it would make more sense to categorize them as nodes that call `_emit` and do not return which unwinds the call stack (synchronous nodes) and nodes that either do not call `_emit` or return before calling `_emit` (asynchronous nodes). The later causes the pipeline to become asynchronous and gives us a reason to track reference counts. All of the async' nodes will handle the reference counters the same way. If data is cached, the counter will be incremented when the data comes in the node and after the data leaves the node, it will be decremented. Sync' nodes will only pass the metadata downstream. This leaves last problem which is how will the async nodes handle the metadata. This is detailed below.

## Synchronous nodes
### Core
* accumulate [Done]
* filter [Done]
* map [Done]
* pluck [Done]
* sink [Done]
* rate_limit [Done]
* slice [Done]
* starmap [Done]
* union [Done]
* unique [Done]
* flatten - The only special case for sync' nodes. The reference to the reference counters can not be duplicated for each messages or their counts will be decremented below zero. Either new reference counters will need to be created for each new data element, or the metadata will need to be emitted only once. If the latter implementation is used, the metadata will be emitted with the last data element as it would make the most sense for check-pointing. 

### Dask
* accumulate [Done]
* map [Done]
* starmap [Done]

## Async' nodes (grouped by strategy)
### Core
#### Input to output is 1:1
Couple the metadata with the data on the cache and pull the metadata off the cache with the data and emit them together.
  * buffer [Done]
  * delay [Done]
  * latest [Done]

#### Input single values and output collections
To increase efficiency, the metadata for the last element can be emitted while the metadata for the other elements can be not emitted. However, this could lead to problems where the metadata for every element is expected downstream. The upstream or unit interested in when the data completes will see the elements that are not at the end of the collection as completed. The less efficient alternative is to cache the metadata with the data and emit the metadata as a collection.
  * collect
  * partition
  * sliding_window
  * timed_window

#### Multiple stream inputs combined into a single output
All datum that is emitted downstream will have it's accompanying metadata emitted with it as a collection.
  * combine_latest
  * zip
  * zip_latest
  
### to_kafka
I'm not yet sure what to do about this node. The `_emit` function is called, but the use of the Confluent library for the callback makes it difficult to match the metadata to the datum. There is also the question as to if we should make any changes here as `to_kafka` should be the end of the pipeline.
  
### Dask
#### A yield is performed before _emit
The metadata is a simple pass-through just as in sync nodes, but the reference counter will need to incremented here as there is a yield before the `_emit` call
  * gather [Done]
  * scatter [Done]

**Comment by jsmaupin** [comment]
Additionally, I currently have a lot of things like this

```python
        if metadata and 'refs' in metadata:
            for ref in metadata['refs']:
                ref.inc(1)
```
I want to see if I can clean this up with Objective-C style `retain` and `release` methods.  The `retain` can implement the `__enter__` and `__exit__` methods to make it usable with the `with` keyword.

**Comment by CJ-Wright** [comment]
I think this looks good, I'll need to read it a few more times (also a prototype implementation PR could be helpful)
