### ISSUE TITLE
Garbage Collection in SDFs

### ISSUE THREAD

**Issue by chinmaychandak** [python-streamz/streamz#321]
If anyone is familiar with the SDFs code base, I was wondering how streamz ensures garbage collection in SDFs.

If a new dataframe comes in, and updates the current state of the SDF, does the dataframe get deleted then and there itself? 

Any help here is appreciated. It would save me a ton of time!

**Comment by martindurant** [comment]
Effectively, yes - when the update is done, the df goes out of scope and gets collected. For aggregation-like nodes, the data is used to make new output, but only the internal "current" df stays in reference by the node. 
In practice, since there can be other nodes processing the same df and things may be happening asynchronously, you cannot guarantee when after the execution of update the df will actually be freed.

**Comment by chinmaychandak** [comment]
Awesome, thank you so much for putting this out here, @martindurant! Appreciate it.
