### ISSUE TITLE
Problem processing dictionary type events using dask-distributed

### ISSUE THREAD

**Issue by pablo-campillo** [python-streamz/streamz#336]
I've realized that events of dict type are not processed properly when using dask-distributed. It seems that only the first event is processed and replicated.

streamz=0.5.3
dask=2.14.0

**Sequential version:**

```python
from streamz import Stream
import random
import time

def my_function(record):
    record['x'] = random.randint(0,100)
    return record

source = Stream()
a = source.map(my_function).sink(print)

for i in range(10):
    source.emit({'i': i})
```

Output:

```
{'i': 0, 'x': 44}
{'i': 1, 'x': 28}
{'i': 2, 'x': 5}
{'i': 3, 'x': 0}
{'i': 4, 'x': 75}
{'i': 5, 'x': 37}
{'i': 6, 'x': 70}
{'i': 7, 'x': 29}
{'i': 8, 'x': 16}
{'i': 9, 'x': 78}
```

**Parallel version:**

```python
from dask.distributed import Client
from streamz import Stream
import random
import time

client = Client()

def my_function(record):
    record['x'] = random.randint(0,100)
    return record

source = Stream()
a = source.scatter().map(my_function).buffer(10).gather().sink(print)

for i in range(10):
    source.emit({'i': i})
```

Output:

```
{'i': 0, 'x': 91}
{'i': 0, 'x': 91}
{'i': 0, 'x': 91}
{'i': 0, 'x': 91}
{'i': 0, 'x': 91}
{'i': 0, 'x': 91}
{'i': 0, 'x': 91}
{'i': 0, 'x': 91}
{'i': 0, 'x': 91}
{'i': 0, 'x': 91}
```

**Comment by CJ-Wright** [comment]
Does this work correctly with just Dask?

**Comment by pablo-campillo** [comment]
I've never used Dask. I've tryed a Dask version and it works, but I don't know if it is equivalent:

```python
from dask.distributed import Client
import random

client = Client()

def my_function(record):
    record['x'] = random.randint(0,100)
    return record

futures = client.map(my_function, [{'i': i} for i in range(10)])
results = client.gather(futures)

print(results)
```

**Comment by martindurant** [comment]
Can you please check what's going on in the dask dashboard? My inkling is, that perhaps the data is not getting tokenised properly, so you are getting the same result back no matter what you send.

**Comment by pablo-campillo** [comment]
You can find bellow the output of the dashboard. Using stream only one task is executed.

Streamz distributed version:

![image](https://user-images.githubusercontent.com/65536570/82888152-46f34b00-9f49-11ea-9ea6-d07ad1099401.png)

Pure dask version:
![image](https://user-images.githubusercontent.com/65536570/82887963-0562a000-9f49-11ea-8751-e04492834684.png)

**Comment by nils-braun** [comment]
So the "problem" here is, that dask behaves differently on `client.scatter` when fed with a dict or a list in contrast to other (normal) objects. 
For example if you call `client.scatter(3)` you will get back a single future (of type int) with a random key.
But if you call `client.scatter([1, 2, 3])` you will actually get back a list of three futures (of type int, all with random key) - and not a future of type list (which itself is maybe already unexpected and only works, because `client.submit` is smart enough to unpack all futures - I do not know if the elements of the list could e.g. end up on different workers)
And if you now call `client.scatter({"a": 1})` as in the example, dask will turn this into (symbolically) `{"a": Future(1)}`, where "a" is used as the key of the Future because this is how you normally want to use `client.scatter` (outside of streamz).

I see two possibilities here: 
* give `client.scatter` in dask an option to leave the input data as it is and to not try to unpack lists or dicts (but treat it as a "blob")
* or always pass in a dictionary by ourselves when streamz calls `scatter` and only return the dictionary value (probably preferred)

What do you think @martindurant @CJ-Wright  @mrocklin ?

**Comment by martindurant** [comment]
I don't think that distributed is interested in changing its API to serve streamz, but clarity around exactly what processing happens there would be good. The examples section of the scatter docstrings does show the cases from above.

From the point of view of the immediate problem, I think wrapping the data is a fine solution.

**Comment by nils-braun** [comment]
Ok, I will do a PR
